const latinToCyrillic = (text: string): string => {
  const latinToCyrillicMap: { [key: string]: string } = {
    A: "А",
    B: "Б",
    V: "В",
    G: "Г",
    D: "Д",
    E: "Е",
    ZH: "Ж",
    Z: "З",
    I: "И",
    Y: "Й",
    K: "К",
    L: "Л",
    M: "М",
    N: "Н",
    O: "О",
    P: "П",
    R: "Р",
    S: "С",
    T: "Т",
    U: "У",
    F: "Ф",
    H: "Х",
    TS: "Ц",
    CH: "Ч",
    SH: "Ш",
    SHCH: "Щ",
    YU: "Ю",
    YA: "Я",
    a: "а",
    b: "б",
    v: "в",
    g: "г",
    d: "д",
    e: "е",
    zh: "ж",
    z: "з",
    i: "и",
    y: "й",
    k: "к",
    l: "л",
    m: "м",
    n: "н",
    o: "о",
    p: "п",
    r: "р",
    s: "с",
    t: "т",
    u: "у",
    f: "ф",
    h: "х",
    ts: "ц",
    ch: "ч",
    sh: "ш",
    shch: "щ",
    yu: "ю",
    ya: "я",
  };

  return text.replace(/([A-Za-z]+|[A-Za-z])/g, (match) => {
    return latinToCyrillicMap[match] || match;
  });
};

export default latinToCyrillic;